### ISSUE TITLE
Format inline code also with Xojo syntax

### ISSUE THREAD

**Issue by XojoGermany** [gkjpettet/xojo-rainbow#4]
Is it somehow possible to use the highlighter also for inline codes?

For example:
Hello ```<pre><code data-language="xojo">&cFFFFFF00</code></pre>``` World!

Unfortunately, the browser always makes the highlighter from it:
```html
Hello 
<pre><code data-language="xojo">&cFFFFFF00</code></pre>
 World!
```
Without ```<pre/>``` the code block is not output in the Xojo syntax.

**Comment by gkjpettet** [comment]
I'm afraid this is a limitation of the Rainbow library, not the Xojo syntax grammar.
